### ISSUE TITLE
ValueError: could not convert string to float: 'T'

### ISSUE THREAD

**Issue by xenhua** [qzhu2017/vasprun#8]
My command `vasprun -v vasprun.xml -d d -s 0.15 -n dos-d.png` producec the following error:

```

Traceback (most recent call last):
  File "/home/xenhua/anaconda3/bin/vasprun", line 4, in <module>
    __import__('pkg_resources').run_script('vasprun-xml==1.0.0', 'vasprun')
  File "/home/xenhua/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/xenhua/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1460, in run_script
    exec(script_code, namespace, namespace)
  File "/home/xenhua/anaconda3/lib/python3.6/site-packages/vasprun_xml-1.0.0-py3.6.egg/EGG-INFO/scripts/vasprun", line 48, in <module>
  File "/home/xenhua/anaconda3/lib/python3.6/site-packages/vasprun_xml-1.0.0-py3.6.egg/vasprun/__init__.py", line 59, in __init__
  File "/home/xenhua/anaconda3/lib/python3.6/site-packages/vasprun_xml-1.0.0-py3.6.egg/vasprun/__init__.py", line 106, in parse_vaspxml
  File "/home/xenhua/anaconda3/lib/python3.6/site-packages/vasprun_xml-1.0.0-py3.6.egg/vasprun/__init__.py", line 140, in parse_finalpos
  File "/home/xenhua/anaconda3/lib/python3.6/site-packages/vasprun_xml-1.0.0-py3.6.egg/vasprun/__init__.py", line 203, in parse_varray
  File "/home/xenhua/anaconda3/lib/python3.6/site-packages/vasprun_xml-1.0.0-py3.6.egg/vasprun/__init__.py", line 203, in <listcomp>
  File "/home/xenhua/anaconda3/lib/python3.6/site-packages/vasprun_xml-1.0.0-py3.6.egg/vasprun/__init__.py", line 203, in <listcomp>
ValueError: could not convert string to float: 'T'

```

**Comment by qzhu2017** [comment]
@xenhua Can you upload your vasprun.xml here?
