### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by cahndengbin** [qzhu2017/vasprun#9]
Traceback (most recent call last):
  File "/home/user/miniconda3/bin/vasprun", line 48, in <module>
    test = vasprun(options.vasprun)
  File "/home/user/miniconda3/lib/python3.7/site-packages/vasprun/__init__.py", line 58, in __init__
    self.parse_vaspxml(doc)
  File "/home/user/miniconda3/lib/python3.7/site-packages/vasprun/__init__.py", line 99, in parse_vaspxml
    self.values["calculation"], scf_count = self.parse_calculation(child)
  File "/home/user/miniconda3/lib/python3.7/site-packages/vasprun/__init__.py", line 393, in parse_calculation
    tdos, pdos = self.parse_dos(i)
  File "/home/user/miniconda3/lib/python3.7/site-packages/vasprun/__init__.py", line 346, in parse_dos
    if len(dos.find("partial"))>0:
TypeError: object of type 'NoneType' has no len()

**Comment by qzhu2017** [comment]
@cahndengbin 
Can you upload your vasprun.xml here?
